name: Deploy DAGs to Airflow VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Copy files via SSH
        uses: appleboy/scp-action@v0.1.1
        with:
          host: your_vm_ip
          username: eanrosenko
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "dags/*"
          target: "/home/eanrosenko/airflow/dags/"
